TOPMODULE=memcpy
RTL=memcpy.v
TEST=testbench.v
USERTEST=--usertest=$(TEST)
ROOTDIR=../../
MEM=$(ROOTDIR)/mem-incr.hex
MEMIMG=--memimg=$(MEM)
#SKIP=--skip_not_found
#IGNORE=--ignore_protocol_error
CONFIG=$(ROOTDIR)/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/base.mk
